name: CI

on: [push, pull_request]

jobs:
  ubuntu-build:
    name: Ubuntu CI
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y libao-dev libfftw3-dev librtlsdr-dev python3-pyaudio
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Compile
        working-directory: build
        run: make -j3
      - name: Windows cross-compile
        run: |
          sudo apt-get install -y mingw-w64
          support/win-cross-compile 32
          support/win-cross-compile 64
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build
          path: /nrsc5/
  macos-build:
    name: MacOS CI
    strategy:
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
          brew install autoconf automake libtool libao fftw librtlsdr portaudio
          # pip3 install --global-option=build_ext --global-option="-I/usr/local/include/" --global-option="-L/usr/local/lib" pyaudio
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Compile
        working-directory: build
        run: make -j3
      - name: Windows cross-compile
        run: |
          brew install --cask xquartz wine-stable
          brew install mingw-w64
          support/win-cross-compile 32
          support/win-cross-compile 64
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: /nrsc5/
